basicapp/urls.py
from django.urls import path
from basicapp import views

#Template tagging
app_name = 'basicapp'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls')),
]

basicapp/models.py
from django.db import models

# Create your models here.

basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {
        'text':'hello world',
        'number':100,
    }
    return render(request, 'basicapp/index.html', context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_templates.html')

templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welvo</title>
  </head>
  <body>
    <h1>Welcome to BASE</h1>
  </body>
</html>

templates/basicapp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <!-- <h1>Welcome to INDEX</h1> -->
    <h1>{{ text|cut:'hello' }}</h1>
    <h1>{{ number|add:"99" }}</h1>

  </body>
</html>

templates/basicapp/other.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to OTHER</h1>
    
  </body>
</html>

templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <h1>Welcome to RELATIVE</h1>
    <a href="{% url 'basicapp:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">ADmin Page</a>
    <a href="{% url 'index' %}">Index page</a>

  </body>
</html>